### ISSUE TITLE
Oauth timestamp is not valid

### ISSUE THREAD

**Issue by AguinaldoAranda** [dnetix/masterpass#5]
Hello, Diego.

I'm trying to use the code from your repository, but it always returns the following at the time of creating the token:

Description: Oauth timestamp is not valid
ReasonCode: INVALID_TIMESTAMP
Source: OAuth.Timestamp
Response Code 403

This same problem occurs when I try to deploy with the masterpass SDK, but I still have not got support back.

I have a lot of urgency in this process, could you please help me if you have any idea what might be causing this timestamp error?

Thank you.

**Comment by dnetix** [comment]
Hello
By the error message I could guess that its a date time problem, please check if the server's date it's synchronized with the world time, that time can't be different by approximately 5 minutes.
If the problem persist or the server's date time its ok, just write me again to make another validation with a server of mine.
Best regards.

**Comment by dnetix** [comment]
Just to check, please run this php code and paste the response if the problem persist

`echo shell_exec('curl https://dnetix.co/helper/diff?datetime=' . date('c'));`

Note that you need to have curl installed on your server and if you have ssh access to the server just run it inline
`php -r "echo shell_exec('curl https://dnetix.co/helper/diff?datetime=' . date('c'));";`

**Comment by AguinaldoAranda** [comment]
Hello Diego, very grateful for your help.

I had set the date_default_timezone_set () in the program and it was not working, I adjusted the server time and it worked.

I never thought that date_default_timezone_set () directly in the program would not solve, but at last is ok now, thanks anyway.
